[package]
name = "eight_characters_app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus = "0.3.1"
dioxus-desktop = "0.3.0"
eight_characters_lib = { path = "../eight_characters_lib" }